# Generated by Django 4.0.3 on 2022-03-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD1App', '0002_baka_baptiste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baka_baptiste',
            name='nom',
            field=models.CharField(max_length=20),
        ),
    ]
