# Generated by Django 2.2.25 on 2022-05-08 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD1App', '0004_delete_baka_baptiste_machine_mach_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=7)),
                ('maintenanceDate', models.DateField(default=datetime.datetime(2022, 5, 8, 17, 0, 0, 532927))),
                ('mach', models.CharField(choices=[('Technicien', 'aime sa famille'), ('Directeur', 'aime sa famille et l argent'), ('PDG', 'aime l argent')], default='Technicien', max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 8, 17, 0, 0, 514787)),
        ),
    ]
