# Generated by Django 2.2.25 on 2022-05-08 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD1App', '0005_auto_20220508_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 8, 17, 17, 51, 624204)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 8, 17, 17, 51, 606783)),
        ),
    ]
