# Generated by Django 4.0.3 on 2022-05-24 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD1App', '0007_alter_employe_mach_alter_employe_maintenancedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 24, 12, 47, 33, 925213)),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nom',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 24, 12, 47, 33, 902996)),
        ),
    ]
