# Generated by Django 4.0.3 on 2022-06-13 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD1App', '0009_remove_employe_maintenancedate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id_c', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=17)),
                ('prenom', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('poste', models.CharField(choices=[('Technicien', 'Tecnicien'), ('User', 'Utilisateur')], default='User', max_length=15)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id_e', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Type', models.CharField(choices=[('Ordinateur', 'Ordinateur'), ('Switch', 'Commutateur'), ('Routeur', 'Router')], default='Ordinateur', max_length=15)),
                ('infra', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=17)),
                ('maj', models.DateField(default=datetime.datetime(2022, 6, 13, 22, 6, 25, 739502))),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id_i', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('entreprise', models.CharField(max_length=30)),
                ('responsable', models.CharField(max_length=17)),
            ],
        ),
        migrations.AlterField(
            model_name='employe',
            name='Date_DE_NAISSANCE',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 22, 6, 25, 738713)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 22, 6, 25, 713945)),
        ),
    ]
