# Generated by Django 4.0.3 on 2022-06-13 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD1App', '0010_compte_equipement_infrastructure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='Date_DE_NAISSANCE',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 22, 10, 22, 443694)),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='Type',
            field=models.CharField(choices=[('Ordinateur', 'Ordinateur'), ('Serveur', 'Serveur'), ('Switch', 'Commutateur'), ('Routeur', 'Router')], default='Ordinateur', max_length=15),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='maj',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 22, 10, 22, 444487)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 22, 10, 22, 421776)),
        ),
    ]
