# Generated by Django 4.0.3 on 2022-06-13 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD1App', '0011_alter_employe_date_de_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='Entretien',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 22, 18, 11, 456846)),
        ),
        migrations.AlterField(
            model_name='employe',
            name='Date_DE_NAISSANCE',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 22, 18, 11, 456209)),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='maj',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 22, 18, 11, 457165)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 22, 18, 11, 423081)),
        ),
    ]
