# Generated by Django 4.0.3 on 2022-06-14 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD1App', '0016_alter_employe_date_de_naissance_alter_equipement_maj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='Entretien',
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='entretien',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 0, 48, 52, 313456)),
        ),
        migrations.AlterField(
            model_name='employe',
            name='Date_DE_NAISSANCE',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 0, 48, 52, 312858)),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='maj',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 0, 48, 52, 313954)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 0, 48, 52, 291847)),
        ),
    ]
