# Generated by Django 4.0.3 on 2022-06-14 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD1App', '0017_remove_infrastructure_entretien_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employe',
        ),
        migrations.AlterField(
            model_name='equipement',
            name='maj',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 1, 50, 43, 533671)),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='entretien',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 1, 50, 43, 533384)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 1, 50, 43, 507787)),
        ),
    ]
