# Generated by Django 4.0.3 on 2022-06-14 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD1App', '0018_delete_employe_alter_equipement_maj_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.AlterField(
            model_name='equipement',
            name='maj',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 3, 37, 21, 894850)),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='entretien',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 3, 37, 21, 894506)),
        ),
    ]
